templates = [
    'a photo of a {}.',
    'a photo of the {}.',
    'a photo of one {}.',
    'a photo of my {}.',
    'a photo of a cool {}.',
    'a photo of the cool {}.',
    'a photo of a small {}.',
    'a photo of the small {}.',
    'a photo of a large {}.',
    'a photo of the large {}.',
    'a photo of a nice {}.',
    'a photo of the nice {}.',
    'a photo of a weird {}.',
    'a photo of the weird {}.',
    'a photo of a clean {}.',
    'a photo of the clean {}.',
    'a photo of a dirty {}.',
    'a photo of the dirty {}.',
    'a photo of a hard to see {}.',
    'a photo of the hard to see {}.',
    'a bad photo of a {}.',
    'a bad photo of the {}.',
    'a black and white photo of a {}.',
    'a black and white photo of the {}.',
    'a blurry photo of a {}.',
    'a blurry photo of the {}.',
    'a bright photo of a {}.',
    'a bright photo of the {}.',
    'a dark photo of a {}.',
    'a dark photo of the {}.',
    'a close-up photo of a {}.',
    'a close-up photo of the {}.',
    'a cropped photo of a {}.',
    'a cropped photo of the {}.',
    'a low resolution photo of a {}.',
    'a low resolution photo of the {}.',
    'a jpeg corrupted photo of a {}.',
    'a jpeg corrupted photo of the {}.',
    'a good photo of a {}.',
    'a good photo of the {}.',
    'a pixelated photo of a {}.',
    'a pixelated photo of the {}.',
    'a drawing of a {}.',
    'a drawing of the {}.',
    'itap of a {}.',
    'itap of my {}.',
    'itap of the {}.',
    'a photo of many {}.',
    'a tattoo of a {}.',
    'a tattoo of the {}.',
    'a embroidered {}.',
    'the embroidered {}.',
    'a painting of a {}.',
    'a painting of the {}.',
    'a sculpture of a {}.',
    'a sculpture of the {}.',
    'a rendition of a {}.',
    'a rendition of the {}.',
    'a rendering of a {}.',
    'a rendering of the {}.',
    'a {} in a video game.',
    'the {} in a video game.',
    'a sketch of a {}.',
    'a sketch of the {}.',
    'a doodle of a {}.',
    'a doodle of the {}.',
    'a origami {}.',
    'the origami {}.',
    'a cartoon {}.',
    'the cartoon {}.',
    'art of a {}.',
    'art of the {}.',
    'graffiti of a {}.',
    'graffiti of the {}.',
    'a toy {}.',
    'the toy {}.',
    'a plastic {}.',
    'the plastic {}.',
    'a plushie {}.',
    'the plushie {}.',
]

class_templates = [
    "{}",
    "bird on {}",
    "bird on a {}",
    "bird and a {}",
    "fowl on {}",
    "fowl on a {}",
    "fowl and a {}",
]

class_keywords_all = [
    [
        "forest",
        "woods",
        "tree",
        "branch",
    ],
    [
        "ocean",
        "beach",
        "surfer",
        "boat",
        "dock",
        "water",
        "lake",
    ]
]